using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.UI;

/*
 * HOW RESEARCH WILL WORK?
 * 
 * Research points will able to generated by player from start of medieval age when books invented
 * University contract has to be completed also.
 * 
 * 
 * 
 */

public class ResearchManager : Singleton<ResearchManager>
{
    List<ScriptableResearch> researchList;

    void CheckResearches()
    {
        for (int i = 0; i < researchList.Count; i++)
        {
            var inputs = researchList[i].researchItems.Zip(researchList[i].requiredResourceAmounts, (item, amount) => (Item: item, Amount: amount));

            foreach (var (Item, Amount) in inputs)
            {

            }
        }
    }

    // Need a lots of improvement
    #region Node Creation
    public Vector2 testPosition;
    [SerializeField] Transform parent;

    public GameObject CreateNode(Vector2 position)
    {
        var node = new GameObject("Node");
        var img = node.AddComponent<Image>();
        img.color = Color.red;
        node.transform.SetParent(parent);
        node.GetComponent<RectTransform>().sizeDelta = new Vector2(256, 256);
        node.transform.localPosition = position;
        node.transform.localScale = Vector3.one;
        return node;
    }

    public void CreateChildNode(GameObject parentNode)
    {
        var childNode = CreateNode(new Vector2(parentNode.transform.position.x, parentNode.transform.position.y + 64));
        CreateConnection(parentNode, childNode);
    }

    void CreateConnection(GameObject obj1, GameObject obj2)
    {
        var connection = new GameObject("Connection");
        var img = connection.AddComponent<Image>();
        img.color = Color.blue;

        img.GetComponent<RectTransform>().sizeDelta =
            new Vector2(20, Mathf.Abs(obj1.transform.position.y - obj2.transform.position.y));

        if (obj1.transform.position.x > obj2.transform.position.x)
            connection.transform.Rotate(0, 0, -45);
        else
            connection.transform.Rotate(0, 0, 45);

        connection.transform.position = new Vector3(obj1.transform.position.x - obj2.transform.position.x, obj1.transform.position.y - obj2.transform.position.y, 0);
    }
    #endregion
}

public enum ResearchItem
{
    Gastronomy,
    Combat,
    Gathering,
    Building,
    Economy,
    Engineering,
    Science,
    Space,
}